# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/ecc.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(997, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.warffwa = QtWidgets.QLabel(self.centralwidget)
        self.warffwa.setGeometry(QtCore.QRect(410, 20, 361, 81))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.warffwa.setFont(font)
        self.warffwa.setObjectName("warffwa")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(100, 120, 81, 21))
        self.label_3.setMinimumSize(QtCore.QSize(0, 21))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 21))
        self.label_3.setObjectName("label_3")
        self.plainTextEdiaaw = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdiaaw.setGeometry(QtCore.QRect(180, 120, 601, 101))
        self.plainTextEdiaaw.setObjectName("plainTextEdiaaw")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(110, 330, 81, 21))
        self.label_5.setMinimumSize(QtCore.QSize(0, 21))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 21))
        self.label_5.setObjectName("label_5")
        self.plainTextEdit_4efgd = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_4efgd.setGeometry(QtCore.QRect(180, 300, 611, 111))
        self.plainTextEdit_4efgd.setObjectName("plainTextEdit_4efgd")
        self.pushButton_3feraf = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3feraf.setGeometry(QtCore.QRect(390, 510, 111, 31))
        self.pushButton_3feraf.setObjectName("pushButton_3feraf")
        self.pushButton_eegge_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_eegge_2.setGeometry(QtCore.QRect(130, 510, 101, 31))
        self.pushButton_eegge_2.setObjectName("pushButton_eegge_2")
        self.pushButton_eegge_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_eegge_3.setGeometry(QtCore.QRect(260, 510, 101, 31))
        self.pushButton_eegge_3.setObjectName("pushButton_eegge_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 997, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.warffwa.setText(_translate("MainWindow", "ECC CIPHER"))
        self.label_3.setText(_translate("MainWindow", "Information: "))
        self.label_5.setText(_translate("MainWindow", "Signature:"))
        self.pushButton_3feraf.setText(_translate("MainWindow", "Generate keys"))
        self.pushButton_eegge_2.setText(_translate("MainWindow", "sign"))
        self.pushButton_eegge_3.setText(_translate("MainWindow", "verify"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
